# general settings
name: train_claritywarenet
model_type: ClarityAwareMoeModel
scale: 1
num_gpu: auto
manual_seed: 0

# USM the ground-truth
l1_gt_usm: False
percep_gt_usm: False
gan_gt_usm: False

high_order_degradation: False # do not use the high-order degradation generation process

# dataset and data loader settings
datasets:
  train:
    name: DDPD_train_c
    type: CMoeImageDataset
    dataroot_gt: /home/guider/data/sr/DDPD/train_c/target
    dataroot_lq: /home/guider/data/sr/DDPD/train_c/coarse
    dataroot_cond: /home/guider/data/sr/DDPD/train_c/source
    io_backend:
      type: disk

    gt_size: 512
    use_flip: True
    use_rot: False

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 1
    batch_size_per_gpu: 5
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  # Uncomment these for validation
  val:
    name: validation
    type: CMoeImageDataset
    dataroot_gt: /home/guider/data/sr/DDPD/test_c/target
    dataroot_lq: /home/guider/data/sr/DDPD/test_c/coarse_test
    dataroot_cond: /home/guider/data/sr/DDPD/test_c/source
    io_backend:
      type: disk

# network structures
network_g:
  type: PCAMoENet
  in_channel: 6
  out_channel: 3
  width: 32
  enc_blk_nums: [1, 1, 8]
  middle_blk_num: 1
  dec_blk_nums: [1, 1, 8]
  patch_size: 64 # 分块大小
  K: 4 # 四种专家

# clarity estimator
network_c:
  type: ClarityEstimator
  in_chan: 3
  patch_size: 64 # 需要保持和PCAMoENet配置相同
  scale_level: 4
  module_num: 8
  module_chan: 32
  middle_feat: 15
  num_class: 4 # 四种退化类别
  num_experts: 4 #四种专家，需要保持和PCAMoENet配置相同


# path
path:
  # use the pre-trained Real-ESRNet model
  pretrain_network_g: ~
  param_key_g: params_ema
  strict_load_g: true
  pretrain_network_c: ~
  param_key_c: params
  strict_load_c: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_c:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [840_000]
    gamma: 0.5

  total_iter: 840_000
  warmup_iter: 10_000  # no warm up
  ema_decay: 0.999


  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: !!float 0.0
    reduction: mean
  # content loss
  content_opt:
    type: SSIMLoss
    data_range: 1.0
    size_average: True
    channel: 3
    loss_weight: !!float 1.0

  # clarity loss
  clarity_opt:
    type: CrossEntropyLoss
    loss_weight: !!float 1.0


  net_d_iters: 1
  net_d_init_iters: 0

# Uncomment these for validation
# validation settings
val:
  val_freq: !!float 200
  save_img: True

  metrics:
    psnr: # metric name
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

    ssim: # metric name
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 200
  use_tb_logger: false
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
